---
name: Deploy to GitHub Pages
on: # Memicu workflow saat ada push ke branch main dan file index.html berubah
  push:
    branches:
      - main
    paths:
      - 'src/index.html'
      - 'src/**'
      - '.github/workflows/deploy.yaml'
jobs:
  deploy:
    environment:  # Menentukan environment untuk deployment untuk GitHub Pages agar dapat mengakses URL halaman yang dideploy
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:  # Memberikan izin yang diperlukan untuk mengakses repository dan melakukan deployment ke GitHub Pages
      contents: read
      pages: write
      id-token: write
    steps:  # Langkah-langkah untuk melakukan checkout repository, mengupload artifact, dan melakukan deployment ke GitHub Pages
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Prepare static files
        run: |
          mkdir -p _site
          cp -R src/* _site/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: # Mengupload file dari direktori src sebagai artifact untuk digunakan dalam langkah deployment
          name: github-pages
          path: '_site'
          retention-days: 1
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
        with: # Menggunakan artifact yang telah diupload untuk melakukan deployment ke GitHub Pages
          artifact_name: github-pages
